<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LessonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('lessons')->delete();
        $data = [            
            [
                'lesson_name' => 'The 12 Basic English Tenses (Simple present)',
                'weekday' => '1',
                'start_time' => '10:00',
                'end_time'   => '12:00',
                'course_id' => '1',
                'teacher_id' => '2',
            ],
            [
                'lesson_name' => 'The 12 Basic English Tenses (Present continuous)',
                'weekday' => '2',
                'start_time' => '10:00',
                'end_time'   => '12:00',
                'course_id' => '1',
                'teacher_id' => '2',
            ],
            [
                'lesson_name' => 'The 12 Basic English Tenses (Present perfect continuous)',
                'weekday' => '3',
                'start_time' => '10:00',
                'end_time'   => '12:00', 
                'course_id' => '1',
                'teacher_id' => '2',
            ],
            [
                'lesson_name' => 'The 12 Basic English Tenses (Present perfect)',
                'weekday' => '4',
                'start_time' => '10:00',
                'end_time'   => '12:00',
                'course_id' => '1',
                'teacher_id' => '2',
            ],
            [
                'lesson_name' => 'The 12 Basic English Tenses (Simple past)',
                'weekday' => '5',
                'start_time' => '10:00',
                'end_time'   => '12:00', 
                'course_id' => '1',
                'teacher_id' => '2',
            ],
            [
                'lesson_name' => 'English Advanced (Grammar 1)',
                'weekday' => '1',
                'start_time' => '08:00',
                'end_time'   => '10:00',
                'course_id' => '2',
                'teacher_id' => '3',
            ],
            [
                'lesson_name' => 'English Advanced (Verb Tenses 1)',
                'weekday' => '3',
                'start_time' => '08:00',
                'end_time'   => '10:00', 
                'course_id' => '2',
                'teacher_id' => '3',
            ],
            [
                'lesson_name' => 'English Advanced (Vocabulary 1)',
                'weekday' => '5',
                'start_time' => '08:00',
                'end_time'   => '10:00', 
                'course_id' => '2',
                'teacher_id' => '3',
            ],
            [
                'lesson_name' => 'Ielts Grammar 1',
                'weekday' => '1',
                'start_time' => '08:00',
                'end_time'   => '10:00', 
                'course_id' => '3',
                'teacher_id' => '4',
            ],
            [
                'lesson_name' => 'Ielts Vocabulary 1',
                'weekday' => '2',
                'start_time' => '08:00',
                'end_time'   => '10:00', 
                'course_id' => '3',
                'teacher_id' => '4',
            ],
            [
                'lesson_name' => 'Ielts Verb Tenses 1',
                'weekday' => '3',
                'start_time' => '08:00',
                'end_time'   => '10:00',
                'course_id' => '3',
                'teacher_id' => '4',
            ],
            [
                'lesson_name' => 'Ielts Reading 1',
                'weekday' => '4',
                'start_time' => '08:00',
                'end_time'   => '10:00',
                'course_id' => '3',
                'teacher_id' => '4',
            ],
            [
                'lesson_name' => 'Ielts Listening 1',
                'weekday' => '5',
                'start_time' => '08:00',
                'end_time'   => '10:00',
                'course_id' => '3',
                'teacher_id' => '4',
            ],
            [
                'lesson_name' => 'Toeic Verb Tenses 1',
                'weekday' => '2',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '4',
                'teacher_id' => '5',
            ],
            [
                'lesson_name' => 'Toeic Vocabulary 1',
                'weekday' => '4',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '4',
                'teacher_id' => '5',
            ],
            [
                'lesson_name' => 'PTE Vocabulary 1',
                'weekday' => '1',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '5',
                'teacher_id' => '6',
            ],
            [
                'lesson_name' => 'PTE Grammar 1',
                'weekday' => '2',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '5',
                'teacher_id' => '6',
            ],
            [
                'lesson_name' => 'PTE Verb 1',
                'weekday' => '3',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '5',
                'teacher_id' => '6',
            ],
            [
                'lesson_name' => 'PTE Listeng 1',
                'weekday' => '4',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '5',
                'teacher_id' => '6',
            ],
            [
                'lesson_name' => 'PTE Reading 1',
                'weekday' => '5',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '5',
                'teacher_id' => '6',
            ],
            [
                'lesson_name' => 'Korean Basic Vocabulary 1',
                'weekday' => '1',
                'start_time' => '9:00',
                'end_time'   => '11:00',
                'course_id' => '6',
                'teacher_id' => '7',
            ],
            [
                'lesson_name' => 'Korean Basic Grammar 1',
                'weekday' => '3',
                'start_time' => '9:00',
                'end_time'   => '11:00', 
                'course_id' => '6',
                'teacher_id' => '7',
            ],
            [
                'lesson_name' => 'Korean Basic Practice 1',
                'weekday' => '5',
                'start_time' => '9:00',
                'end_time'   => '11:00', 
                'course_id' => '6',
                'teacher_id' => '7',
            ],
            [
                'lesson_name' => 'Korean Advanced Vocabulary 1',
                'weekday' => '1',
                'start_time' => '13:00',
                'end_time'   => '15:00', 
                'course_id' => '7',
                'teacher_id' => '8',
            ],
            [
                'lesson_name' => 'Korean Advanced Grammar 1',
                'weekday' => '3',
                'start_time' => '13:00',
                'end_time'   => '15:00', 
                'course_id' => '7',
                'teacher_id' => '8',
            ],
            [
                'lesson_name' => 'Korean Advanced Practice 1',
                'weekday' => '5',
                'start_time' => '13:00',
                'end_time'   => '15:00', 
                'course_id' => '7',
                'teacher_id' => '8',
            ],
            [
                'lesson_name' => 'TOPIK Vocaburaly 1',
                'weekday' => '1',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '8',
                'teacher_id' => '9',
            ],
            [
                'lesson_name' => 'TOPIK Grammar 1',
                'weekday' => '5',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '8',
                'teacher_id' => '9',
            ],
            [
                'lesson_name' => 'TOPIK Verb 1',
                'weekday' => '5',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '8',
                'teacher_id' => '9',
            ],
            [
                'lesson_name' => 'TOPIK Tense 1',
                'weekday' => '5',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '8',
                'teacher_id' => '9',
            ],
            [
                'lesson_name' => 'TOPIK Practice 1',
                'weekday' => '5',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '8',
                'teacher_id' => '9',
            ],
            [
                'lesson_name' => 'KLAT II Vocabulary 1',
                'weekday' => '1',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '9',
                'teacher_id' => '10',
            ],
            [
                'lesson_name' => 'KLAT II Grammar 1',
                'weekday' => '2',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '9',
                'teacher_id' => '10',
            ],
            [
                'lesson_name' => 'KLAT II Listening 1',
                'weekday' => '3',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '9',
                'teacher_id' => '10',
            ],
            [
                'lesson_name' => 'KLAT II Reading 1',
                'weekday' => '4',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '9',
                'teacher_id' => '10',
            ],
            [
                'lesson_name' => 'KLAT II Practice 1',
                'weekday' => '5',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '9',
                'teacher_id' => '10',
            ],
            [
                'lesson_name' => 'KLAT III Vocabulary 1',
                'weekday' => '1',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '10',
                'teacher_id' => '11',
            ],
            [
                'lesson_name' => 'KLAT III Grammar 1',
                'weekday' => '2',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '10',
                'teacher_id' => '11',
            ],
            [
                'lesson_name' => 'KLAT III Listening 1',
                'weekday' => '3',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '10',
                'teacher_id' => '11',
            ],
            [
                'lesson_name' => 'KLAT III Reading 1',
                'weekday' => '4',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '10',
                'teacher_id' => '11',
            ],
            [
                'lesson_name' => 'KLAT III Practice 1',
                'weekday' => '5',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '10',
                'teacher_id' => '11',
            ],
            [
                'lesson_name' => 'Japanese Basic (Minna no nihongo 1)',
                'weekday' => '1',
                'start_time' => '17:00',
                'end_time'   => '19:00', 
                'course_id' => '11',
                'teacher_id' => '12',
            ],
            [
                'lesson_name' => 'Japanese Basic (Minna no nihongo 2)',
                'weekday' => '2',
                'start_time' => '17:00',
                'end_time'   => '19:00', 
                'course_id' => '11',
                'teacher_id' => '12',
            ],
            [
                'lesson_name' => 'Japanese Basic (Minna no nihongo 3)',
                'weekday' => '3',
                'start_time' => '17:00',
                'end_time'   => '19:00', 
                'course_id' => '11',
                'teacher_id' => '12',
            ],
            [
                'lesson_name' => 'Japanese Basic (Minna no nihongo 4)',
                'weekday' => '4',
                'start_time' => '17:00',
                'end_time'   => '19:00', 
                'course_id' => '11',
                'teacher_id' => '12',
            ],
            [
                'lesson_name' => 'Japanese Basic (Practice)',
                'weekday' => '5',
                'start_time' => '17:00',
                'end_time'   => '19:00', 
                'course_id' => '11',
                'teacher_id' => '12',
            ],
            [
                'lesson_name' => 'Japanese Advanced (Minna no nihongo 26)',
                'weekday' => '1',
                'start_time' => '17:00',
                'end_time'   => '19:00', 
                'course_id' => '12',
                'teacher_id' => '13',
            ],
            [
                'lesson_name' => 'Japanese Advanced (Minna no nihongo 27)',
                'weekday' => '2',
                'start_time' => '17:00',
                'end_time'   => '19:00', 
                'course_id' => '12',
                'teacher_id' => '13',
            ],
            [
                'lesson_name' => 'Japanese Advanced (Minna no nihongo 28)',
                'weekday' => '3',
                'start_time' => '17:00',
                'end_time'   => '19:00', 
                'course_id' => '13',
                'teacher_id' => '13',
            ],
            [
                'lesson_name' => 'Japanese Advanced (Minna no nihongo 29)',
                'weekday' => '4',
                'start_time' => '17:00',
                'end_time'   => '19:00', 
                'course_id' => '12',
                'teacher_id' => '13',
            ],
            [
                'lesson_name' => 'Japanese Advanced (Practice)',
                'weekday' => '5',
                'start_time' => '17:00',
                'end_time'   => '19:00', 
                'course_id' => '12',
                'teacher_id' => '13',
            ],
            [
                'lesson_name' => 'JLPT N1 Vocabulary 1',
                'weekday' => '1',
                'start_time' => '10:00',
                'end_time'   => '12:00', 
                'course_id' => '13',
                'teacher_id' => '14',
            ],
            [
                'lesson_name' => 'JLPT N1 Grammar 1',
                'weekday' => '3',
                'start_time' => '10:00',
                'end_time'   => '12:00', 
                'course_id' => '13',
                'teacher_id' => '14',
            ],
            [
                'lesson_name' => 'JLPT N1 Practice 1',
                'weekday' => '5',
                'start_time' => '10:00',
                'end_time'   => '12:00', 
                'course_id' => '13',
                'teacher_id' => '14',
            ],
            [
                'lesson_name' => 'JLPT N2 Vocabulary 1',
                'weekday' => '1',
                'start_time' => '10:00',
                'end_time'   => '12:00', 
                'course_id' => '14',
                'teacher_id' => '15',
            ],
            [
                'lesson_name' => 'JLPT N2 Grammar 1',
                'weekday' => '3',
                'start_time' => '10:00',
                'end_time'   => '12:00', 
                'course_id' => '14',
                'teacher_id' => '15',
            ],
            [
                'lesson_name' => 'JLPT N2 Practise 1',
                'weekday' => '5',
                'start_time' => '10:00',
                'end_time'   => '12:00', 
                'course_id' => '14',
                'teacher_id' => '15',
            ],
            [
                'lesson_name' => 'JLPT N3 Vocabulary 1',
                'weekday' => '1',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '15',
                'teacher_id' => '16',
            ],
            [
                'lesson_name' => 'JLPT N3 Grammar 1',
                'weekday' => '2',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '15',
                'teacher_id' => '16',
            ],
            [
                'lesson_name' => 'JLPT N3 Vocabulary 2',
                'weekday' => '3',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '15',
                'teacher_id' => '16',
            ],
            [
                'lesson_name' => 'JLPT N3 Grammar 2',
                'weekday' => '4',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '15',
                'teacher_id' => '16',
            ],
            [
                'lesson_name' => 'JLPT N3 Practice 1',
                'weekday' => '5',
                'start_time' => '18:00',
                'end_time'   => '20:00', 
                'course_id' => '15',
                'teacher_id' => '16',
            ],

            
        ];
        DB::table('lessons')->insert($data);
    }
}
